# Generated by Django 2.1.1 on 2019-05-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Post')),
            ],
        ),
    ]
